### ISSUE TITLE
LS init issue

### ISSUE THREAD

**Issue by gokhanozdemir** [aleyna-yildizli/hellokedy-pro#1]
https://github.com/aleyna-yildizli/hellokedy-pro/blob/37cb8550baee93099c8db27e18c21611e2bc69c7/src/App.jsx#L49C3-L49C8

```javascript
    const value = favCats.length === 0 ? [] : favCats;
``` 

Favs array olmalı.

**Comment by aleyna-yildizli** [comment]
Done
